#!/usr/bin/env python3
"""Generate og.png, the 1200x630 social card.  Run:  python3 make_og.py

og.png has three lines of type baked into its pixels, so it goes stale in a
way no build step notices: paste degel.com anywhere and the preview shows
whatever was true when the PNG was made. On 2026-08-27 the page began leading
with "Fractional CTO" while the card still said "Software Consultant", and the
headline contradicted its own image for ten days (website-5mm.5).

The first card was generated by something that was never committed -- the
DECISIONS.md note says "generated (Palatino Bold + era-spectrum waves)" and
`git log -- og.png` shows one commit adding a binary. So the layout had to be
measured back out of the PNG. This file exists so that never happens twice.

EVERY NUMBER BELOW WAS MEASURED FROM THE ORIGINAL og.png (41204 bytes, the
single commit that added it), not invented: colours sampled, text bounding
boxes located, font sizes solved by fitting rendered width to the measured
ink width, flag corners read off pixel by pixel. The intent is to reproduce
that composition exactly and change only what is actually out of date.

Every colour is a token from src/_style.html's light theme rather than a
literal picked to match -- the card and the page it previews must not drift
apart, and the original's pixels agree with the tokens exactly.

Pillow is the one dependency here, and it is a BUILD-TIME dependency of a
file that is committed as a binary. Nothing the site serves depends on it,
and `make build` does not run this: the card changes about once a year, and
regenerating it on every build would rewrite a 40KB binary in every commit.
"""

import math
import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

W, H = 1200, 630
SS = 3  # supersample factor for the vector shapes; PIL polygons have no AA

# --- palette: src/_style.html, light theme -----------------------------------
PAPER = (0xDA, 0xEA, 0xE9)  # --paper, the Zircon Ice ground
INK = (0x17, 0x20, 0x2D)  # --ink
MUTED = (0x3F, 0x4B, 0x5D)  # --muted
FAINT = (0x4F, 0x5D, 0x73)  # --faint
ACCENT = (0x00, 0x38, 0xB8)  # --accent, the flag blue

# --- the era spectrum, recovered from the original PNG ------------------------
# The card does NOT reuse the home page's waveband paths; its curves are much
# flatter (10px of amplitude against the page's 67). The original generator was
# never committed, so the curves were fitted back out of the published pixels:
# six sines, one period across the width, and the fit is regular enough to be
# certain it IS the original formula rather than an approximation of it --
# 14.0px between midlines, 0.9rad of phase between bands, one shared
# amplitude, and a worst-case residual under 1px across all 1200 columns.
#
# The colours are not stored as literals. Painting --w1..--w6 at these alphas
# over --paper reproduces all six composited band colours in the original
# EXACTLY, channel for channel, which is what proves the card was always the
# site's own era spectrum rather than a set of hand-picked lookalikes.
BAND_MID0 = 519.6  # midline of the topmost band
BAND_STEP = 14.0  # and of each band below it
BAND_AMP = 9.885
BAND_PHASE_STEP = 0.9  # radians; the stagger that makes them read as waves
# --w1..--w6, light theme. The last is the AI era and the accent, and carries
# nearly twice the alpha of the rest -- the same emphasis the page's own
# waveband gives it.
WAVES = [
    ((0x6D, 0x28, 0xD9), 0.431),
    ((0x0C, 0x65, 0x5C), 0.431),
    ((0xA8, 0x38, 0x0A), 0.431),
    ((0xBE, 0x18, 0x5D), 0.431),
    ((0x0F, 0x65, 0x30), 0.431),
    ((0x00, 0x38, 0xB8), 0.785),
]

# --- type: sizes and baselines solved against the original's ink boxes -------
TTC = "/System/Library/Fonts/Palatino.ttc"
BOLD, REGULAR = 2, 0  # face indices within the collection; 1 is Italic
LINES = [
    ("David Goldfarb", BOLD, 108, 90, 238, INK),
    ("Fractional CTO · Degel Software", REGULAR, 47, 94, 331, MUTED),
    ("Every technology wave since 1980 — now at AI speed", REGULAR, 33, 95, 409, FAINT),
]

# --- the flag mark, corners read off the original ----------------------------
POLE = (1047, 120, 1054, 260)  # x0, y0, x1, y1
BANNER = [(1058, 128), (1150, 148), (1150, 196), (1058, 176)]

root = pathlib.Path(__file__).resolve().parent


def band_top(k, x):
    """The y of band k's top edge at column x. One sine, one period across."""
    return (
        BAND_MID0
        + BAND_STEP * k
        + BAND_AMP * math.sin(2 * math.pi * x / W + BAND_PHASE_STEP * k)
    )


def draw_shapes():
    """The spectrum and the flag, supersampled then reduced. PIL fills
    polygons with hard edges, and at this size a stair-stepped wave is the
    first thing the eye finds."""
    layer = Image.new("RGBA", (W * SS, H * SS), PAPER + (255,))
    for k, (rgb, alpha) in enumerate(WAVES):
        # Each band runs to the bottom edge and is painted over the ones
        # above it, so the visible colour of each is a composite of every
        # band down to it -- which is exactly how the original was built.
        pts = [(x, band_top(k, x / SS) * SS) for x in range(W * SS + 1)]
        pts += [(W * SS, H * SS), (0, H * SS)]
        band = Image.new("RGBA", layer.size, (0, 0, 0, 0))
        ImageDraw.Draw(band).polygon(pts, fill=rgb + (round(alpha * 255),))
        layer = Image.alpha_composite(layer, band)

    im = layer.convert("RGB")
    dr = ImageDraw.Draw(im)
    dr.rectangle([c * SS for c in POLE], fill=MUTED)
    dr.polygon([(x * SS, y * SS) for x, y in BANNER], fill=ACCENT)
    return im.resize((W, H), Image.LANCZOS)


def main():
    if not pathlib.Path(TTC).exists():
        sys.exit(f"missing font: {TTC} (this script assumes macOS system fonts)")
    im = draw_shapes()
    dr = ImageDraw.Draw(im)
    # Text is drawn at final size, not supersampled: PIL renders glyphs with
    # its own antialiasing and hinting, and downsampling that muddies it.
    for text, face, size, x, baseline, colour in LINES:
        dr.text(
            (x, baseline),
            text,
            font=ImageFont.truetype(TTC, size, index=face),
            fill=colour,
            anchor="ls",
        )
    out = root / "og.png"
    im.save(out, optimize=True)
    print(f"wrote {out.relative_to(root)}: {W}x{H}, {out.stat().st_size} bytes")
    for text, *_ in LINES:
        print(f"  {text}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
